version: "3.8"
services:

  users:
      container_name: users-service
      build: ./users-service/docker
      ports:
          - "9000:8000"
      volumes:
          - ./users-service:/var/www
      networks:
      - dev
  notifications:
      container_name: notifications-service
      build: ./notifications-service/docker
      ports:
          - "9001:8001"
      volumes:
          - ./notifications-service:/var/www
      networks:
      - dev     

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_name
    ports:
      - 3306:3306
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: sf_phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev
networks:
  dev: