<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container43IAcXP\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container43IAcXP/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container43IAcXP.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container43IAcXP\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container43IAcXP\App_KernelProdContainer([
    'container.build_hash' => '43IAcXP',
    'container.build_id' => '3be06bdf',
    'container.build_time' => 1722523549,
], __DIR__.\DIRECTORY_SEPARATOR.'Container43IAcXP');
