<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA6T3GsO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA6T3GsO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA6T3GsO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA6T3GsO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA6T3GsO\App_KernelDevDebugContainer([
    'container.build_hash' => 'A6T3GsO',
    'container.build_id' => 'e7d476e1',
    'container.build_time' => 1722523996,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA6T3GsO');
