<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'create_user' => [[], ['_controller' => 'App\\Controller\\UserController::createUser'], [], [['text', '/users']], [], [], []],
];
