version: "3.8"
services:

  php8:
      container_name: notifications-service
      build: docker
      ports:
          - "9001:8000"
      volumes:
          - ./:/var/www
      networks:
      - dev
networks:
  dev: