version: "3.8"
services:

  notifications:
      container_name: notifications-service
      build: docker
      ports:
          - "9001:8001"
      volumes:
      - ./notifications:/var/www
      networks:
      - dev1
networks:
  dev1: